version: '3.7'
services:
    postgres:
      container_name: postgres
      image: postgres:14.3-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432
      volumes: 
        - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgres-data:/var/lib/postgresql/data